[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pylint.format]
max-line-length = 88

[tool.pylint."messages control"]
disable = "missing-docstring"

[tool.isort]
# Use default isort settings.
